import os
print("WebSend Installer")
print("==================")
input("Press 'Return' to begin: ")
print("Creating virtual python environment...")
os.system("python -m venv WS")
print("==================")
print("Installing dependencies...")
os.system("source WS/bin/activate && pip install -r requirements.txt")
print("==================")
print("Making run.sh executable...")
os.system("chmod +x run.sh")
print("Done")
input("Press 'Return' to quit: ")
quit()
